### ISSUE TITLE
Modification aware basecalling for long read workflow

### ISSUE THREAD

**Issue by borgesadair1** [Arcadia-Science/metagenomics#17]
Would be great to have the option to do methylation detection for bacterial + phage genomes using Nanopore.

**Comment by elizabethmcd** [comment]
Ideas: 
- Plot summarizing read length and error rate, highlighting or put to the side reads that are above some length but have high error rates
- Remora for methylation/modified base calling based on training on a model: https://github.com/nanoporetech/remora 
- Bonito basecaller with modified base tags and can view them in IGV https://github.com/nanoporetech/bonito/blob/master/documentation/SAM.md

**Comment by borgesadair1** [comment]
Talked to Rachel and Emily about this, and one of their contacts recommended this: https://github.com/fanglab/nanodisco
Comes from this paper which is really cool: https://pubmed.ncbi.nlm.nih.gov/33820988/

This method requires sequencing native DNA + WGA DNA, so we are adding WGA libraries to select communities to generate some test data for demoing this method.

**Comment by elizabethmcd** [comment]
Going to close this for now as it is outside the scope of this workflow. Could be integrated elsewhere
