### ISSUE TITLE
Workflow name

### ISSUE THREAD

**Issue by elizabethmcd** [Arcadia-Science/metagenomics#2]
Potentially change repo and workflow name to just `metagenomics-nf` as when you run with `nextflow run Arcadia-Science/arcadia-metagenomic-assembly-nf ....` the Arcadia part is redundant in the repo/workflow name. However if you clone the repository and run with `nextflow run main.nf` then the repo name would just be `metagenomics-nf`. 

It depends on what the suggested "quick start" run should be, as not requiring `git clone` is a faster start. Forking or cloning would more suggest that somebody is contributing changes to the pipeline and not running it persay. 

The other issue is if `metagenomics-nf` alone is enough description, as this just covers the QC, assembly, and evaluation of metagenomic reads/assembly. It doesn't imply subsequent binning for example, which would be a separate workflow `binning-nf` for example under this nomenclature strategy. 

@taylorreiter thoughts?

**Comment by taylorreiter** [comment]
what about `metagenomics-assembly-nf`? Then subsequent pipelines could include key words for what those things do (e.g. `metagenomics-binning-nf` and `metagenomes-annotation-nf`).

I agree that arcadia is redundant. I would prefer if the suggested quickstart does not involve `git clone`. That gets really cumbersome when the nf workflow is only one piece of a larger analysis. However, I'm still new to running nf pipelines so it's hard for me to have strong opinions here.

**Comment by elizabethmcd** [comment]
Ok I agree on `metagenomics-assembly-nf` for this one and `metagenomics-binning-nf` for the subsequent workflow. I think I will keep annotation as `microbial-annotation-nf` so it's clear you can input a microbial genome from any source (isolate or MAG)

**Comment by elizabethmcd** [comment]
Workflow name is changed to `metagenomics` to be all lower case, and one word with no punctuation. This conforms to nf-core practices when creating and naming pipelines with `nf-core create, according to issues` https://github.com/nf-core/tools/issues/85 and https://github.com/nf-core/tools/pull/1822
