### ISSUE TITLE
sourmash integration

### ISSUE THREAD

**Issue by elizabethmcd** [Arcadia-Science/metagenomics#5]
### Description of feature

Add Nextflow modules for sourmash sketch, compare, gather, etc. for reads and assemblies 
- Sourmash sketch module updated with nf-core and PR approved

Integrate resulting sourmash files with Taylor's sourmashconsumr R package when ready for creating reports

**Comment by taylorreiter** [comment]
the nf-core taxprofile pipeline has been doing work on sourmash so lots of the modules we need are in the process of being updated or created:

* sourmash sketch:
    * PR: https://github.com/nf-core/modules/pull/2176
* sourmash gather: 
    * PR: https://github.com/nf-core/modules/pull/2250
    * issue: https://github.com/nf-core/modules/issues/2214
* sourmash taxonomy:
    * issue: https://github.com/nf-core/modules/issues/2261

**Comment by vmikk** [comment]
@taylorreiter Hello Taylor!
`sourmash tax annotate` module was merged to nf-core yesterday. Could you please test it on your data?
Also we are thinking to add `sourmash summarize` module, but I'm not sure how fast I'll do it.

**Comment by elizabethmcd** [comment]
addressed in #46 for sourmash infrastructure, issue #30 will include gather/taxonomy for db comparison and summaries
